# -*- coding: utf-8 -*-
"""dbs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10C7THJCfeHxQp8Otr6JqHdhY0Lx1DoRN
"""

#import os
#import cv2
#from PIL import Image
#import numpy as np
#from matplotlib import pyplot as plt
#import csv
#import pickle
#import tensorflow as tf
#from sklearn.cluster import DBSCAN
#from sklearn.metrics import silhouette_score
#import glob

#from google.colab import drive
#drive.mount('/content/gdrive')

#trainingp = "/content/gdrive/MyDrive/Colab Notebooks/Penguins-vs-Turtles/Datasets/train/train"
#validp = "/content/gdrive/MyDrive/Colab Notebooks/Penguins-vs-Turtles/Datasets/valid/valid"
#with open('/content/gdrive/MyDrive/Colab Notebooks/Penguins-vs-Turtles/Datasets/train.csv', 'r') as f:
#with open('/content/gdrive/MyDrive/Colab Notebooks/Penguins-vs-Turtles/Datasets/valid.csv', 'r') as f:

#dbs = DBSCAN(eps=3, min_samples=3).fit(train_data)
#dbresult = dbs.predict()
#with open('data.pkl', 'wb',) as f:
    #pickle.dump(dbresult, f)